### ISSUE TITLE
Nav Icon help

### ISSUE THREAD

**Issue by voldf0598** [voldf0598/kraken-good-accessibility#1]
I can't seem to get the nav icons to show up!!

@hellachella @HannahDelaney

**Comment by HannahDelaney** [comment]
I'll check it out!

**Comment by voldf0598** [comment]
thank you!

**Comment by HannahDelaney** [comment]
Oooohhhh so this is a server issue. The icons are actually showing but the way svg works, there's like a security issue that won't display them, so you have to use your local server to see them.

Put the assignment into Markbot, and there is a little eyeball icon at the top left. Click on that and it will open through your local server, and you'll get a security page, but click on "Advanced" at the bottom and "Proceed" to see your site, and the icons should appear! (Don't do this on just any site because it could lead you to unsafe sites, but here we know it's safe because it's from our computer.)

I tested it and could see them.

**Comment by HannahDelaney** [comment]
Thomas explains it a bit here:

https://learn-the-web.algonquindesign.ca/courses/web-dev-3/using-svg-icons/#step-6

**Comment by voldf0598** [comment]
okay ill try that

**Comment by voldf0598** [comment]
thank you so much!

**Comment by voldf0598** [comment]
It worked!!

**Comment by HannahDelaney** [comment]
Thank _you_ for being a bit ahead — I think every single person will have this problem and now Chelle and I can get on top of it before everyone is overwhelmed.

Also, amazing! Happy to hear.
